source_stream_name = "stg_recommender_events"
output_stream_name = "stg_recommender_predictions"
model_bucket = "stg-mlflow-models-code-owners-feranmi"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "stg_recommender_system"
lambda_function_name = "stg_prediction_lambda"
